checklist
anton-zm/sprint-12 pull request #1
Opened 2020-06-12 10:42 UTC by anton-zm

Проектная работа № 12. 
Учились строить GET запросы на сервер и отвечать на них.

2020-06-12 13:42 UTC, mrprovoker requested changes
### Добрый день!

Отличная работа!

Отлично:
- все роуты обрабатываются корректно;
- код чистый, структура проекта логичная;

---
### Надо исправить:
- Если запустить проверку линтера, исключая проверку директорий `node_modules` и `public` (например, командой `node_modules/.bin/eslint --ext=.js ./ --ignore-pattern "public/"`) то будет 23 ошибки линтера. *Ошибок линтера в проекте быть не должно.*

### *Можно лучше:*
- В файле `package.json` рекомендуется заполнить секцию **description**.
Подробнее про секцию можно прочитать в официальной документации [по данной ссылке.](https://docs.npmjs.com/files/package.json#description)

- В routes/cards.js используется fs.readFile через колбек, а в routes/cards.js через promise. Рекомендуется в проекте использовать единую схему работу с файлами. 

- Не рекомендуется использовать однобуквенные переменные кроме общепринятых случаев. Например, вместо `(await usersArr()).find((e)` можно было написать `(await usersArr()).find((user)`, чтобы стало понятнее, что содержится в перменной у метода find.

- Расскажите, почему используется условие `  if (!res.headersSent) {` в функции urlNotFound в файле `app.js`?

---

2020-06-13 07:31 UTC, anton-zm commented
Здравствуйте, Сергей! Я исправил ошибки линтера, а также, учел все Ваши рекомендации и внес соответствующие правки. 
Что же касается использования headersSent, то тут история простая. Я пытался реализовать функцию при помощи if(!req.url), но ничего не работало. Стал гуглить свойства объектов запроса и ответа. И в одном из обсуждений нашел такой вариант. Я строчку if(!res.headersSent) понимаю так: если по такому запросу не было ответа (а по несуществующему адресу ответа на было), то отвечаем так-то.

2020-06-14 05:17 UTC, mrprovoker approved these changes
Спасибо за правки. Теперь работа отличная.

Оставил вам рекомендацию по поводу линтера. 

---
Все пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*

2020-06-14 05:17 UTC, mrprovoker commented on routes/users.js
> +/* eslint-disable */
Можно лучше:

- В тех случаях когда правила необходимо отключать для одной строки, как например с `no-underscore-dangle`, то рекомендуется использовать отключение через `// eslint-disable-next-line no-underscore-dangle`, писав непосредственно перед строкой кода.
В данном же случае строчкой `eslint-disable` отключается линтер полностью, что плохо, так как есть возможность пропустить некоторые ошибки.

- Насчет ошибки `arrow-body-style` линтер рекомендует заменить функцию на такую запись: 
   ```js
   const usersArr = async () => (JSON.parse(await fs.readFile(users, { encoding: 'utf8' })));
   ```

2020-06-14 05:58 UTC, merged